### ISSUE TITLE
Situation with "kheops" in url

### ISSUE THREAD

**Issue by ylemarechal** [lassoan/SlicerDICOMwebBrowser#8]
Hello,

I installed kheops on a private server but dicomweb calls from Slicer don't work without a manual modification of generated links from kheops  because of the check here :
https://github.com/lassoan/SlicerDICOMwebBrowser/blob/7bd6b3269e92e816b63054af10293af4efc7fc76/DICOMwebBrowser/DICOMwebBrowser.py#L545-L548
A suggestion, as a quick fix, could be to replace this line
https://github.com/lassoan/SlicerDICOMwebBrowser/blob/7bd6b3269e92e816b63054af10293af4efc7fc76/DICOMwebBrowser/DICOMwebBrowser.py#L552
by something like
`effectiveServerUrl = url.url().replace(url.path(),'') + "/api"`

According to your opinion, there would be the same modification to be made on the DICOMLib side here
https://github.com/Slicer/Slicer/blob/3584ca084f1bf897eba441ba4ea34b960aa1fc34/Modules/Scripted/DICOMLib/DICOMProcesses.py#L472

Regards
Yannick

**Comment by lassoan** [comment]
The suggested changes make sense. Would you mind submitting a pull request?

**Comment by lassoan** [comment]
Fixed in https://github.com/lassoan/SlicerDICOMwebBrowser/pull/17
